app_name = "{{cookiecutter.app_name}}"
app_port = "8080"
db_host = "0.0.0.0"
db_password = "postgres"
db_username = "postgres"


[debug]
db_name = "{{cookiecutter.app_name}}_development"
db_port = "5432"

[test]
db_name = "{{cookiecutter.app_name}}_test"
db_port = "5433"
