version: "3.5"

services:
  db:
    image: postgres:12.3
    container_name: xxxx_db
    environment:
      - POSTGRES_DB=xxxx_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
