version: "3.5"

services:
  db_test:
    image: postgres:14.2
    container_name: {{cookiecutter.app_name}}_db_test
    environment:
      - POSTGRES_DB={{cookiecutter.app_name}}_test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
