name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x

      - name: Create ENV file
        run: cp ".env.test" ".env"

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Install dependencies
        run: make install-dependencies

      - name: Test
        run: make test
