name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install cookiecutter
        run: sudo apt-get install cookiecutter

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.x

      - name: Test
        run: make test
