name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: GITHUB REF
        run: |
          echo ${GITHUB_REF#refs/heads/}

      - name: Install cookiecutter
        run: sudo apt-get install cookiecutter

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Test
        env:
          GOPATH: /home/runner/go
        run: BRANCH=${BRANCH_NAME} make test

